### ISSUE TITLE
Can't press Start Streaming

### ISSUE THREAD

**Issue by TATDK** [WatchBeam/ftl-studio#18] opened 2016-05-17 19:33 UTC
Nothing happens when pressing Start Streaming

Dist and stream key is set correctly.
Tachyon version 1.0
Windows 10 Pro N
64 bit

Log file - https://gist.github.com/2d6302b4a28cf3d1692e653aebbdb549
I can see some .dll files couldn't be found, this already happens at startup

**Comment by TATDK** [comment] 2016-05-17 19:35
Also, when applying new stream key - the application crashes

**Comment by TATDK** [comment] 2016-05-17 19:37
And on exit and application crash, the program is still running in the background
![image](https://cloud.githubusercontent.com/assets/636270/15336575/6defb2a6-1c77-11e6-9ba5-bbe9b63b257b.png)

When trying to kill it, it gives me an "Access is denied" error
![image](https://cloud.githubusercontent.com/assets/636270/15336588/87430bf4-1c77-11e6-958e-33ca996f7a38.png)

**Comment by myiume** [comment] 2016-05-18 14:17
Also experiencing this. The start stream button not working. I don't get access denied when trying to kill it, but sometimes it just stops responding out of a sudden.

**Comment by sslivins** [comment] 2016-05-19 00:07
can you go to the follow site on your computer and paste the 'Share Your Results here:
http://www.speedguide.net/analyzer.php

**Comment by myiume** [comment] 2016-05-19 01:18
« SpeedGuide.net TCP Analyzer Results » 
Tested on: 2016.05.18 21:17 
IP address: 86.125.xx.xx 
Client OS/browser: Windows 10 (Chrome 50.0.2661.102) 

TCP options string: 020405a00103030801010402 
MSS: 1440 
MTU: 1480 
TCP Window: 66048 (NOT multiple of MSS) 
RWIN Scaling: 8 bits (2^8=256) 
Unscaled RWIN : 258 
Recommended RWINs: 63360, 126720, 253440, 506880, 1013760 
BDP limit (200ms): 2642kbps (330KBytes/s)
BDP limit (500ms): 1057kbps (132KBytes/s) 
MTU Discovery: ON 
TTL: 113 
Timestamps: OFF 
SACKs: ON 
IP ToS: 00000000 (0)

**Comment by TATDK** [comment] 2016-05-19 15:04
```
« SpeedGuide.net TCP Analyzer Results » 
Tested on: 2016.05.19 11:03 
IP address: 194.255.xx.xx 
Client OS/browser: Windows 10 (Chrome 50.0.2661.102) 

TCP options string: 020405b40103030801010402 
MSS: 1460 
MTU: 1500 
TCP Window: 65536 (NOT multiple of MSS) 
RWIN Scaling: 8 bits (2^8=256) 
Unscaled RWIN : 256 
Recommended RWINs: 64240, 128480, 256960, 513920, 1027840 
BDP limit (200ms): 2621kbps (328KBytes/s)
BDP limit (500ms): 1049kbps (131KBytes/s) 
MTU Discovery: ON 
TTL: 111 
Timestamps: OFF 
SACKs: ON 
IP ToS: 00000000 (0) 
```

**Comment by sslivins** [comment] 2016-05-20 18:46
please try v1.0.1 in the releases tab.  I do not expect it will fix all situations, but in the cases above the mtu size was larger than what your network allowed and thus would have been dropped resulting in no stream.  If the above release does not fix your issue please let me know and we can delve deeper

**Comment by TATDK** [comment] 2016-05-20 19:04
Works with v1.0.1

**Comment by sslivins** [comment] 2016-05-20 19:23
glad to hear that, thanks for the quick feedback

**Comment by myiume** [comment] 2016-05-20 20:11
https://gist.github.com/385a0d7972a5b54e823e1afd55cd90fa

same issue still. Pressing Start Streaming does nothing. No errors nothing.

Also, trying to do any changes in the output settings tab makes the program stop responding. Restarting it shows the change before pressing apply, but it now works to be changed once, and then it stops responding again.

**Comment by sslivins** [comment] 2016-05-25 17:43
@myiume my apologies for not getting back to you sooner.  I would suggest trying 1.1 but i dont think it will resolve the issue.  The logs looks clean other than your video format should be i420 instead of NV12 but that wont cause whats happening here.  I would actually really like to get to the bottom of this  so can you reach out to support at beam.pro/contact and mention this github ticket and we'll start digging deeper

**Comment by myiume** [comment] 2016-06-02 21:36
Resolved in version 1.1.2

**Comment by pinghajen** [comment] 2016-06-03 03:15
Check to see if you have AVG running, If you do try making and exception in AVG for OBS to get through the firewall.

**Comment by SkippTekk** [comment] 2016-06-03 21:22
i have well got this issue, i even used an old FTL code for the servers to detect that the stream key is wrong, even that isn't working. my AVG is also allowing the program to access the internet, never had this issue for a while actually.

Computer Specs : https://i.gyazo.com/60f59ff897a249af88ec0f262b341eb0.png

**Comment by sslivins** [comment] 2016-06-03 21:36
i havent published 1.1.2 yet but you're welcome to try it to see if this resolves your issue:

https://www.dropbox.com/s/o54tek1ea53di1m/Tachyon_Installer_1.1.2.exe?dl=0

if this doesnt work for you please open an official ticket via beam.pro/contact

**Comment by SkippTekk** [comment] 2016-06-03 21:49
@sslivins hey man, i also noticed, that when the installer removed the Tachyon from the computer, it doesn't stop it's ENTIRE service so i have to go into my Task Manager and remove 3 services of it so the installer can modify the file "avcodect-57.dll" maybe patch this later?

**Comment by SkippTekk** [comment] 2016-06-03 21:52
1.1.2 Has fixed the issue, thank you very much! :D

**Comment by sslivins** [comment] 2016-06-03 22:36
@SkippTekk i'm aware of the installer not working when the process is still running.  it is on the todo list. 

Glad to hear the issue is fixed for you.  the ftl handshake was considered malformed by some antivirus or antimalware tools so i have corrected that in this version

**Closed as completed** 2016-06-09 04:43 UTC

**Comment by mikey150** [comment] 2016-09-30 15:42
someone help me am getting the same issue plz help
